// Copyright (c) 2025 Matheus Degiovani. All rights reserved.
// Use of this source code is governed by a source-available
// license that can be found in the LICENSE file.

package mdcapnp

import "time"

// SmallTestStruct is a handwritten small test structure.
type SmallTestStruct Struct

func (st *SmallTestStruct) Siblings() int64 {
	return (*Struct)(st).Int64(0)
}

func (st *SmallTestStruct) ReadNameField(ls *List) error {
	return (*Struct)(st).ReadList(0, ls) // First pointer.
}

// GoserbenchSmallStruct is a handwritten (i.e. not generated by the capnp
// compiler) implementation of goserbench's SmallStruct benchmark structure.
type GoserbenchSmallStruct Struct

func (st *GoserbenchSmallStruct) ReadFromRoot(msg *Message) error {
	return msg.ReadRoot((*Struct)(st))
}

func (st *GoserbenchSmallStruct) ReadNameField(ls *List) error {
	return (*Struct)(st).ReadList(0, ls) // First pointer.
}

func (st *GoserbenchSmallStruct) Name() string {
	return (*Struct)(st).String(0)
}

func (st *GoserbenchSmallStruct) UnsafeName() string {
	return (*Struct)(st).UnsafeString(0)
}

func (st *GoserbenchSmallStruct) BirthDay() int64 {
	return (*Struct)(st).Int64(0)
}

func (st *GoserbenchSmallStruct) Phone() string {
	return (*Struct)(st).String(1)
}

func (st *GoserbenchSmallStruct) UnsafePhone() string {
	return (*Struct)(st).UnsafeString(1)
}

func (st *GoserbenchSmallStruct) Siblings() int32 {
	return (*Struct)(st).Int32(1, Int32FieldLo)
}

func (st *GoserbenchSmallStruct) Spouse() bool {
	return (*Struct)(st).Bool(1, 32)
}

func (st *GoserbenchSmallStruct) Money() float64 {
	return (*Struct)(st).Float64(2)
}

// goserbenchSmallStruct is a copy of goserbench's SmallStruct benchmark
// structure.
type goserbenchSmallStruct struct {
	Name     string
	BirthDay time.Time
	Phone    string
	Siblings int
	Spouse   bool
	Money    float64
}
